name: "Unt_Tests"
on:
  push:
    branches: ["cicd_409340"]
  pull_request:
    branches: ["cicd_409340"]

jobs:
  ubuntu_unt_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install py
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: run unt test 
        run: |
          python -m unittest "circleTest.py"
          python -m unittest "squareTest.py"
          python -m unittest "triangleTest.py"
          python -m unittest "rectangleTest.py"
  windows_unt_test:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install py 
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: run unt test
        run: |
          python -m unittest "circleTest.py"
          python -m unittest "squareTest.py"
          python -m unittest "triangleTest.py"
          python -m unittest "rectangleTest.py"
